/**
 * Showcase / demo stores for marketplace appearance when the live catalog is empty.
 * Clearly labeled — not real bookings. User-requested for demo look.
 */

import type { City, Tailor } from "@/types";

export type ShowcaseTailor = Tailor & { is_showcase: true };

export const SHOWCASE_CITIES: City[] = [
  { id: "muscat", name_ar: "مسقط", name_en: "Muscat", tailor_count: 6, lat: 23.588, lng: 58.3829 },
  { id: "salalah", name_ar: "صلالة", name_en: "Salalah", tailor_count: 4, lat: 17.0151, lng: 54.0924 },
  { id: "sohar", name_ar: "صحار", name_en: "Sohar", tailor_count: 3, lat: 24.364, lng: 56.7438 },
  { id: "nizwa", name_ar: "نزوى", name_en: "Nizwa", tailor_count: 2, lat: 22.9333, lng: 57.5333 },
  { id: "sur", name_ar: "صور", name_en: "Sur", tailor_count: 2, lat: 22.5667, lng: 59.5289 },
];

const COVER = (from: string, to: string) =>
  `data:image/svg+xml,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400" viewBox="0 0 640 400">
      <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="${from}"/><stop offset="100%" stop-color="${to}"/>
      </linearGradient></defs>
      <rect width="640" height="400" fill="url(#g)"/>
      <circle cx="520" cy="80" r="90" fill="rgba(255,255,255,0.08)"/>
      <circle cx="80" cy="320" r="120" fill="rgba(0,0,0,0.12)"/>
    </svg>`
  )}`;

export const SHOWCASE_STORES: ShowcaseTailor[] = [
  {
    id: "showcase-asalah",
    profile_id: "showcase-asalah",
    name_ar: "خياط الأصالة",
    name_en: "Al Asala Tailoring",
    city_id: "salalah",
    city: "صلالة",
    rating: 4.9,
    review_count: 127,
    starting_price: 12,
    delivery_days: 3,
    specializations: ["traditional", "dishdasha", "formal"],
    specializations_ar: ["تراثي", "دشداشة", "رسمي"],
    verified: true,
    cover_image: COVER("#071a33", "#0f7654"),
    description_ar: "دشداشة عمانية فاخرة وتطريز يدوي — عرض تجريبي للمظهر.",
    description_en: "Premium Omani dishdasha — showcase store for appearance.",
    gallery: [],
    availability_status: "available_now",
    is_showcase: true,
  },
  {
    id: "showcase-muscat-house",
    profile_id: "showcase-muscat-house",
    name_ar: "دار مسقط للتفصيل",
    name_en: "Muscat Tailoring House",
    city_id: "muscat",
    city: "مسقط",
    rating: 4.8,
    review_count: 203,
    starting_price: 15,
    delivery_days: 2,
    specializations: ["premium", "formal", "abaya"],
    specializations_ar: ["فاخر", "رسمي", "عبايات"],
    verified: true,
    cover_image: COVER("#0c2340", "#c8a45d"),
    description_ar: "عبايات ودشداشات فاخرة في قلب مسقط — متجر تجريبي.",
    description_en: "Premium abayas & dishdashas in Muscat — demo store.",
    gallery: [],
    availability_status: "accepting_orders",
    is_showcase: true,
  },
  {
    id: "showcase-salalah-modern",
    profile_id: "showcase-salalah-modern",
    name_ar: "خياط صلالة الحديث",
    name_en: "Salalah Modern Tailor",
    city_id: "salalah",
    city: "صلالة",
    rating: 4.7,
    review_count: 89,
    starting_price: 10,
    delivery_days: 4,
    specializations: ["modern", "casual", "dishdasha"],
    specializations_ar: ["عصري", "يومي", "دشداشة"],
    verified: true,
    cover_image: COVER("#1f5c45", "#0c2340"),
    description_ar: "قصّات عصرية بلمسة عمانية — عرض للمظهر فقط.",
    description_en: "Modern cuts with Omani touch — appearance demo.",
    gallery: [],
    availability_status: "available_now",
    is_showcase: true,
  },
  {
    id: "showcase-nizwa-heritage",
    profile_id: "showcase-nizwa-heritage",
    name_ar: "تراث نزوى",
    name_en: "Nizwa Heritage Atelier",
    city_id: "nizwa",
    city: "نزوى",
    rating: 4.85,
    review_count: 64,
    starting_price: 14,
    delivery_days: 5,
    specializations: ["traditional", "embroidery", "dishdasha"],
    specializations_ar: ["تراثي", "تطريز", "دشداشة"],
    verified: true,
    cover_image: COVER("#7a1f1f", "#071a33"),
    description_ar: "تطريز تراثي دقيق — متجر تجريبي للواجهة.",
    description_en: "Heritage embroidery — showcase store.",
    gallery: [],
    availability_status: "accepting_orders",
    is_showcase: true,
  },
  {
    id: "showcase-sohar-coast",
    profile_id: "showcase-sohar-coast",
    name_ar: "خياطة ساحل صحار",
    name_en: "Sohar Coast Tailors",
    city_id: "sohar",
    city: "صحار",
    rating: 4.6,
    review_count: 51,
    starting_price: 9,
    delivery_days: 4,
    specializations: ["casual", "summer", "dishdasha"],
    specializations_ar: ["يومي", "صيفي", "دشداشة"],
    verified: false,
    cover_image: COVER("#1a4a6b", "#d4c4a8"),
    description_ar: "أقمشة صيفية خفيفة — عرض تجريبي.",
    description_en: "Light summer fabrics — demo appearance.",
    gallery: [],
    availability_status: "busy",
    is_showcase: true,
  },
  {
    id: "showcase-sur-atelier",
    profile_id: "showcase-sur-atelier",
    name_ar: "أتيليه صور",
    name_en: "Sur Atelier",
    city_id: "sur",
    city: "صور",
    rating: 4.75,
    review_count: 38,
    starting_price: 11,
    delivery_days: 5,
    specializations: ["abaya", "evening", "premium"],
    specializations_ar: ["عبايات", "سهرات", "فاخر"],
    verified: true,
    cover_image: COVER("#1a1a1a", "#c8a45d"),
    description_ar: "عبايات سهرة أنيقة — متجر تجريبي.",
    description_en: "Evening abayas — showcase only.",
    gallery: [],
    availability_status: "available_now",
    is_showcase: true,
  },
  {
    id: "showcase-qurm-silk",
    profile_id: "showcase-qurm-silk",
    name_ar: "حرير القرم",
    name_en: "Qurum Silk House",
    city_id: "muscat",
    city: "مسقط",
    rating: 4.95,
    review_count: 176,
    starting_price: 22,
    delivery_days: 3,
    specializations: ["silk", "premium", "abaya"],
    specializations_ar: ["حرير", "فاخر", "عبايات"],
    verified: true,
    cover_image: COVER("#2a1840", "#c8a45d"),
    description_ar: "حرير فاخر وعبايات راقية — عرض للمظهر.",
    description_en: "Silk abayas — appearance demo.",
    gallery: [],
    availability_status: "accepting_orders",
    is_showcase: true,
  },
  {
    id: "showcase-bausher-fit",
    profile_id: "showcase-bausher-fit",
    name_ar: "تفصيل بوشر",
    name_en: "Bausher Fit Studio",
    city_id: "muscat",
    city: "مسقط",
    rating: 4.55,
    review_count: 92,
    starting_price: 13,
    delivery_days: 3,
    specializations: ["modern", "fit", "dishdasha"],
    specializations_ar: ["عصري", "قصة مضبوطة", "دشداشة"],
    verified: true,
    cover_image: COVER("#0f7654", "#071a33"),
    description_ar: "قصة مضبوطة بالقياسات الرقمية — تجريبي.",
    description_en: "Precision fit with digital measurements — demo.",
    gallery: [],
    availability_status: "available_now",
    is_showcase: true,
  },
  {
    id: "showcase-dhofar-linen",
    profile_id: "showcase-dhofar-linen",
    name_ar: "كتان ظفار",
    name_en: "Dhofar Linen",
    city_id: "salalah",
    city: "صلالة",
    rating: 4.7,
    review_count: 71,
    starting_price: 10,
    delivery_days: 4,
    specializations: ["linen", "summer", "dishdasha"],
    specializations_ar: ["كتان", "صيفي", "دشداشة"],
    verified: true,
    cover_image: COVER("#d4c4a8", "#0c2340"),
    description_ar: "كتان صيفي خفيف لموسم الخريف — عرض تجريبي.",
    description_en: "Light linen for the season — demo store.",
    gallery: [],
    availability_status: "accepting_orders",
    is_showcase: true,
  },
  {
    id: "showcase-royal-thread",
    profile_id: "showcase-royal-thread",
    name_ar: "الخيط الملكي",
    name_en: "Royal Thread",
    city_id: "muscat",
    city: "مسقط",
    rating: 4.9,
    review_count: 241,
    starting_price: 28,
    delivery_days: 6,
    specializations: ["bridal", "abaya", "embroidery"],
    specializations_ar: ["مناسبات", "عبايات", "تطريز"],
    verified: true,
    cover_image: COVER("#071a33", "#7a1f1f"),
    description_ar: "عبايات مناسبات بتطريز ذهبي — متجر تجريبي للمظهر.",
    description_en: "Occasion abayas with gold embroidery — showcase.",
    gallery: [],
    availability_status: "busy",
    is_showcase: true,
  },
];

export function shouldUseShowcaseStores(liveCount: number): boolean {
  // Explicit off only
  if (process.env.SHOWCASE_STORES === "0") return false;
  // Force on, or when catalog is empty (default for demos/pitches)
  if (process.env.SHOWCASE_STORES === "1") return true;
  return liveCount === 0;
}
