/**
 * @deprecated DEAD / QUARANTINED — DO NOT IMPORT IN PRODUCTION UI.
 * This file contains FAKE tailors, ratings, prices, and gallery paths.
 * Marketplace and AI chat must use PostgreSQL only.
 * Kept only so historical references don't break typecheck if re-imported by mistake —
 * prefer deleting usages and this file entirely.
 */
import type {
  City,
  Tailor,
  Fabric,
  Review,
  Order,
  DemoUser,
  InventoryItem,
  DesignConfig,
  Measurements,
} from "@/types";

/** Fake city counts — NOT for production marketplace */
export const CITIES: City[] = [
  { id: "muscat", name_ar: "مسقط", name_en: "Muscat", tailor_count: 42, lat: 23.588, lng: 58.3829 },
  { id: "salalah", name_ar: "صلالة", name_en: "Salalah", tailor_count: 18, lat: 17.0151, lng: 54.0924 },
  { id: "sohar", name_ar: "صحار", name_en: "Sohar", tailor_count: 12, lat: 24.364, lng: 56.7438 },
  { id: "nizwa", name_ar: "نزوى", name_en: "Nizwa", tailor_count: 9, lat: 22.9333, lng: 57.5333 },
  { id: "sur", name_ar: "صur", name_en: "Sur", tailor_count: 7, lat: 22.5667, lng: 59.5289 },
];

export const TAILORS: Tailor[] = [
  {
    id: "t1",
    profile_id: "tp1",
    name_ar: "خياط الأصالة",
    name_en: "Al Asala Tailoring",
    city_id: "salalah",
    city: "صلالة",
    rating: 4.9,
    review_count: 127,
    starting_price: 12,
    delivery_days: 3,
    specializations: ["formal", "traditional", "abaya"],
    specializations_ar: ["ثياب رسمية", "تراثي", "عبايات"],
    verified: true,
    description_ar: "متخصصون في الدشداشة العمانية والعبايات الرسمية والتقليدية منذ أكثر من 25 عامًا.",
    description_en: "Specialists in Omani dishdashas, abayas, and traditional formal wear for over 25 years.",
    gallery: ["/images/tailor1.jpg"],
  },
  {
    id: "t2",
    profile_id: "tp2",
    name_ar: "خياط صلالة الحديث",
    name_en: "Salalah Modern Tailor",
    city_id: "salalah",
    city: "صلالة",
    rating: 4.7,
    review_count: 89,
    starting_price: 10,
    delivery_days: 4,
    specializations: ["modern", "casual"],
    specializations_ar: ["عصري", "يومي"],
    verified: true,
    description_ar: "خياطة عصرية بلمسة عمانية أصيلة.",
    description_en: "Modern tailoring with authentic Omani touch.",
    gallery: [],
  },
  {
    id: "t3",
    profile_id: "tp3",
    name_ar: "دار مسقط للتفصيل",
    name_en: "Muscat Tailoring House",
    city_id: "muscat",
    city: "مسقط",
    rating: 4.8,
    review_count: 203,
    starting_price: 15,
    delivery_days: 2,
    specializations: ["formal", "premium"],
    specializations_ar: ["رسمي", "فاخر"],
    verified: true,
    description_ar: "دار تفصيل راقية في قلب مسقط.",
    description_en: "Premium tailoring house in the heart of Muscat.",
    gallery: [],
  },
  {
    id: "t4",
    profile_id: "tp4",
    name_ar: "خياط نزوى التراثي",
    name_en: "Nizwa Heritage Tailor",
    city_id: "nizwa",
    city: "نزوى",
    rating: 4.6,
    review_count: 56,
    starting_price: 11,
    delivery_days: 5,
    specializations: ["traditional", "embroidery"],
    specializations_ar: ["تراثي", "تطريز"],
    verified: true,
    description_ar: "حرفيون في التطريز العماني التقليدي.",
    description_en: "Artisans in traditional Omani embroidery.",
    gallery: [],
  },
  {
    id: "t5",
    profile_id: "tp5",
    name_ar: "مركز الأناقة العمانية",
    name_en: "Omani Elegance Center",
    city_id: "muscat",
    city: "مسقط",
    rating: 4.5,
    review_count: 78,
    starting_price: 13,
    delivery_days: 3,
    specializations: ["formal", "modern"],
    specializations_ar: ["رسمي", "عصري"],
    verified: false,
    description_ar: "مركز متكامل للخياطة الرجالية.",
    description_en: "Complete men's tailoring center.",
    gallery: [],
  },
  {
    id: "t6",
    profile_id: "tp6",
    name_ar: "دار البشوت العمانية",
    name_en: "Omani Bisht House",
    city_id: "sohar",
    city: "صحار",
    rating: 4.4,
    review_count: 45,
    starting_price: 14,
    delivery_days: 4,
    specializations: ["traditional", "formal"],
    specializations_ar: ["تراثي", "رسمي"],
    verified: true,
    description_ar: "متخصصون في البشوت والثياب الرسمية.",
    description_en: "Specialists in bisht and formal wear.",
    gallery: [],
  },
  {
    id: "t7",
    profile_id: "tp7",
    name_ar: "خياط صور الفاخر",
    name_en: "Sur Premium Tailor",
    city_id: "sur",
    city: "صur",
    rating: 4.3,
    review_count: 34,
    starting_price: 12,
    delivery_days: 5,
    specializations: ["premium", "formal"],
    specializations_ar: ["فاخر", "رسمي"],
    verified: true,
    description_ar: "تفصيل فاخر بجودة استثنائية.",
    description_en: "Premium tailoring with exceptional quality.",
    gallery: [],
  },
  {
    id: "t8",
    profile_id: "tp8",
    name_ar: "مركز الخياطة السريع",
    name_en: "Quick Tailoring Center",
    city_id: "muscat",
    city: "مسقط",
    rating: 4.2,
    review_count: 112,
    starting_price: 9,
    delivery_days: 2,
    specializations: ["casual", "modern"],
    specializations_ar: ["يومي", "عصري"],
    verified: false,
    description_ar: "تسليم سريع بأسعار منافسة.",
    description_en: "Fast delivery at competitive prices.",
    gallery: [],
  },
  {
    id: "t9",
    profile_id: "tp9",
    name_ar: "خياط الوادي الكبير",
    name_en: "Al Wadi Tailor",
    city_id: "nizwa",
    city: "نزوى",
    rating: 4.6,
    review_count: 67,
    starting_price: 10,
    delivery_days: 4,
    specializations: ["traditional", "casual"],
    specializations_ar: ["تراثي", "يومي"],
    verified: true,
    description_ar: "خياطة تقليدية في قلب نزوى.",
    description_en: "Traditional tailoring in the heart of Nizwa.",
    gallery: [],
  },
  {
    id: "t10",
    profile_id: "tp10",
    name_ar: "دار الأناقة الساحلية",
    name_en: "Coastal Elegance House",
    city_id: "salalah",
    city: "صلالة",
    rating: 4.7,
    review_count: 91,
    starting_price: 13,
    delivery_days: 3,
    specializations: ["formal", "premium"],
    specializations_ar: ["رسمي", "فاخر"],
    verified: true,
    description_ar: "أناقة ساحلية بلمسة عمانية.",
    description_en: "Coastal elegance with Omani touch.",
    gallery: [],
  },
];

export const FABRICS: Fabric[] = [
  { id: "f1", name_ar: "قطن فاخر أبيض", name_en: "Premium White Cotton", type: "cotton", price_per_meter: 3.5, color: "#FFFFFF", season: "all" },
  { id: "f2", name_ar: "كتان صيفي", name_en: "Summer Linen", type: "linen", price_per_meter: 4.2, color: "#F5F0E8", season: "summer" },
  { id: "f3", name_ar: "قماش شتوي", name_en: "Winter Fabric", type: "winter", price_per_meter: 5.0, color: "#E8E0D0", season: "winter" },
  { id: "f4", name_ar: "قطن عماني", name_en: "Omani Cotton", type: "cotton", price_per_meter: 2.8, color: "#FFFFFF", season: "all" },
  { id: "f5", name_ar: "كتان فاخر", name_en: "Premium Linen", type: "linen", price_per_meter: 5.5, color: "#FAFAF5", season: "all" },
];

export const DEMO_CUSTOMER: DemoUser = {
  id: "c1",
  email: "abdullah@demo.om",
  password: "demo123",
  profile: {
    id: "c1",
    email: "abdullah@demo.om",
    full_name: "Abdullah Al Balushi",
    full_name_ar: "عبدالله البلوشي",
    role: "customer",
    city_id: "muscat",
    city: "مسقط",
    phone: "+968 9123 4567",
    created_at: "2025-06-01T00:00:00Z",
  },
};

export const DEMO_TAILOR_USER: DemoUser = {
  id: "tp1",
  email: "tailor@demo.om",
  password: "demo123",
  profile: {
    id: "tp1",
    email: "tailor@demo.om",
    full_name: "Ahmed Al Asala",
    full_name_ar: "أحمد الأصالة",
    role: "tailor",
    city_id: "salalah",
    city: "صلالة",
    created_at: "2024-01-01T00:00:00Z",
  },
  tailor: TAILORS[0],
};

export const DEMO_ADMIN: DemoUser = {
  id: "admin1",
  email: "admin@demo.om",
  password: "demo123",
  profile: {
    id: "admin1",
    email: "admin@demo.om",
    full_name: "Platform Admin",
    full_name_ar: "مسؤول المنصة",
    role: "admin",
    created_at: "2024-01-01T00:00:00Z",
  },
};

export const DEMO_MEASUREMENTS: Measurements = {
  id: "m1",
  user_id: "c1",
  height: 173,
  chest: 98,
  waist: 86,
  shoulder: 44,
  sleeve: 59,
  dishdasha_length: 140,
  confidence: 94,
  is_ai_estimate: true,
  created_at: "2025-08-01T00:00:00Z",
};

export const DEMO_DESIGN: DesignConfig = {
  garmentType: "dishdasha",
  color: "أبيض",
  colorKey: "white",
  fabric: "كتان",
  fabricKey: "linen",
  collar: "كلاسيكية",
  collarKey: "classic",
  embroidery: "ذهبي",
  embroideryKey: "gold",
  name: "ثوب رسمي أبيض",
};

export function generateDemoOrders(): Order[] {
  const statuses: Order["status"][] = [
    "sewing",
    "embroidery",
    "ready",
    "delivered",
    "cutting",
  ];
  return Array.from({ length: 50 }, (_, i) => ({
    id: `order-${i + 1}`,
    customer_id: i < 5 ? "c1" : `c${(i % 50) + 2}`,
    tailor_id: TAILORS[i % TAILORS.length].id,
    design: {
      ...DEMO_DESIGN,
      colorKey: ["white", "offwhite", "beige", "navy"][i % 4],
      color: ["أبيض", "أوف وايت", "بيج", "كحلي"][i % 4],
    },
    measurements: DEMO_MEASUREMENTS,
    status: statuses[i % statuses.length],
    total_price: 12 + (i % 10) * 1.5,
    delivery_days: 2 + (i % 4),
    created_at: new Date(2025, 6, 1 + (i % 30)).toISOString(),
    updated_at: new Date(2025, 7, 1 + (i % 15)).toISOString(),
    tailor: TAILORS[i % TAILORS.length],
    customer_name: i < 5 ? "عبدالله البلوشي" : `عميل ${i + 1}`,
  }));
}

export const DEMO_ORDERS = generateDemoOrders();

export const CUSTOMER_ORDERS = DEMO_ORDERS.filter((o) => o.customer_id === "c1");

export const REVIEWS: Review[] = [
  {
    id: "r1",
    tailor_id: "t1",
    customer_name: "سالم الحارثي",
    rating: 5,
    comment_ar: "تفصيل ممتاز وجودة عالية. أنصح به بشدة.",
    comment_en: "Excellent tailoring and high quality. Highly recommended.",
    created_at: "2025-07-15T00:00:00Z",
  },
  {
    id: "r2",
    tailor_id: "t1",
    customer_name: "محمد الشحي",
    rating: 5,
    comment_ar: "التطريز كان رائعًا والتسليم في الوقت المحدد.",
    comment_en: "Embroidery was amazing and delivery was on time.",
    created_at: "2025-07-10T00:00:00Z",
  },
  {
    id: "r3",
    tailor_id: "t1",
    customer_name: "خالد المعمري",
    rating: 4,
    comment_ar: "خدمة جيدة جدًا، سأطلب مرة أخرى.",
    comment_en: "Very good service, will order again.",
    created_at: "2025-06-20T00:00:00Z",
  },
];

export const INVENTORY: InventoryItem[] = [
  {
    id: "inv1",
    tailor_id: "t1",
    fabric_name_ar: "قماش أبيض فاخر",
    fabric_name_en: "White Premium Fabric",
    current_stock: 12,
    unit: "متر",
    consumption_rate: 1.7,
    ai_forecast_days: 7,
    ai_recommendation_ar: "إعادة طلب 30 مترًا.",
    ai_recommendation_en: "Reorder 30 meters.",
    low_stock: true,
  },
  {
    id: "inv2",
    tailor_id: "t1",
    fabric_name_ar: "كتان صيفي",
    fabric_name_en: "Summer Linen",
    current_stock: 45,
    unit: "متر",
    consumption_rate: 0.8,
    ai_forecast_days: 56,
    ai_recommendation_ar: "المخزون كافٍ حاليًا.",
    ai_recommendation_en: "Stock is sufficient.",
    low_stock: false,
  },
  {
    id: "inv3",
    tailor_id: "t1",
    fabric_name_ar: "خيوط تطريز ذهبية",
    fabric_name_en: "Gold Embroidery Thread",
    current_stock: 8,
    unit: "بكرة",
    consumption_rate: 0.5,
    ai_forecast_days: 16,
    ai_recommendation_ar: "راقب المخزون خلال أسبوعين.",
    ai_recommendation_en: "Monitor stock within two weeks.",
    low_stock: false,
  },
];

export const TESTIMONIALS = [
  {
    name: "سالم الحارثي",
    city: "مسقط",
    text_ar: "من أول قياس إلى آخر غرزة — تجربة سلسة ومريحة. AI ساعدني أختار الخياط المناسب.",
    text_en: "From first measurement to last stitch — smooth experience. AI helped me choose the right tailor.",
    rating: 5,
  },
  {
    name: "فاطمة المعولية",
    city: "صلالة",
    text_ar: "طلبت لزوجي ووفرت وقتي. التتبع كان واضحًا والتسليم في الموعد.",
    text_en: "Ordered for my husband and saved time. Tracking was clear and delivery was on time.",
    rating: 5,
  },
  {
    name: "محمد الشحي",
    city: "نزوى",
    text_ar: "إعادة الطلب بضغطة واحدة — ميزة رائعة. قياساتي محفوظة دائمًا.",
    text_en: "One-click reorder is amazing. My measurements are always saved.",
    rating: 5,
  },
];

export const PLATFORM_STATS = {
  totalCustomers: 2847,
  activeTailors: 88,
  totalOrders: 12543,
  gmv: 234567,
  cities: 5,
  aiUsage: 89,
};

export const ANALYTICS_DATA = {
  popularColors: [
    { name: "أبيض", value: 45 },
    { name: "أوف وايت", value: 22 },
    { name: "بيج", value: 15 },
    { name: "كحلي", value: 10 },
    { name: "أسود", value: 8 },
  ],
  popularFabrics: [
    { name: "كتان", value: 38 },
    { name: "قطني", value: 32 },
    { name: "فاخر", value: 18 },
    { name: "صيفي", value: 12 },
  ],
  ordersByCity: [
    { city: "مسقط", orders: 187 },
    { city: "صلالة", orders: 142 },
    { city: "صحار", orders: 98 },
    { city: "نزوى", orders: 76 },
    { city: "صور", orders: 54 },
  ],
  ordersByMonth: [
    { month: "يناير", orders: 820 },
    { month: "فبراير", orders: 950 },
    { month: "مارس", orders: 1100 },
    { month: "أبريل", orders: 980 },
    { month: "مايو", orders: 1200 },
    { month: "يونيو", orders: 1350 },
    { month: "يوليو", orders: 1280 },
    { month: "أغسطس", orders: 890 },
  ],
  avgOrderValue: 18.2,
  repeatCustomers: 42,
};
