import type { TourStep } from "./types";

/** Main home tour — stores-first layout with floating AI. */
export const MAIN_TOUR_STEPS: TourStep[] = [
  {
    id: "home",
    target: "[data-tour='home-split']",
    titleAr: "كل شيء يبدأ من هنا",
    titleEn: "Everything starts here",
    bodyAr: "المتاجر هي محور خياطك. تصفّح الخياطين الحقيقيين، واستعن بالذكاء عند الحاجة من الزر العائم.",
    bodyEn: "Stores are the heart of Khayyatak. Browse real tailors, and open AI from the floating button when you need it.",
    placement: "auto",
  },
  {
    id: "stores",
    target: "[data-tour='home-stores']",
    titleAr: "اكتشف الخياطين",
    titleEn: "Discover tailors",
    bodyAr: "استعرض المتاجر المسجّلة، أعمالهم، تخصصاتهم، وتقييماتهم — كلها من قاعدة بيانات حقيقية.",
    bodyEn: "Browse registered stores, their work, specialties, and ratings — all from the real database.",
    placement: "auto",
  },
  {
    id: "store-card",
    target: "[data-tour='home-store-card']",
    titleAr: "بطاقة المتجر",
    titleEn: "Store card",
    bodyAr: "كل بطاقة تمثل متجرًا حقيقيًا. اضغط «زيارة المتجر» لترى المنتجات والأقمشة والأعمال.",
    bodyEn: "Each card is a real store. Tap Visit store to see products, fabrics, and portfolio.",
    placement: "auto",
    caveatAr: "إن لم تنضم متاجر بعد، تظهر متاجر تجريبية للمظهر فقط — ليست حجوزات حقيقية.",
    caveatEn: "If no live stores yet, labeled demo stores appear for appearance only — not real bookings.",
  },
  {
    id: "ai",
    target: "[data-tour='home-ai-fab']",
    titleAr: "مستشارك الذكي",
    titleEn: "Your AI concierge",
    bodyAr: "الذكاء موجود كزر عائم واضح — لا يسرق مساحة المتاجر. اضغطه لفتح تجربة البحث الذكي.",
    bodyEn: "AI lives as a clear floating button — it doesn’t steal store space. Tap to open smart search.",
    placement: "auto",
    openAi: false,
  },
  {
    id: "ai-demo",
    target: "[data-tour='home-ai-input']",
    titleAr: "الذكاء يبحث لك",
    titleEn: "AI searches for you",
    bodyAr: "مثال: «أبغى دشداشة بيضاء رسمية وصيفية» — يفهم الطلب ويبحث في المنتجات والمتاجر الحقيقية.",
    bodyEn: "Example: “I want a formal summer white dishdasha” — it understands and searches real products and stores.",
    placement: "auto",
    openAi: true,
    demo: "ai-search",
  },
  {
    id: "media",
    target: "[data-tour='home-ai-controls']",
    titleAr: "صوت · صورة · ابتكار",
    titleEn: "Voice · Photo · Innovate",
    bodyAr: "ارفع صورة للإلهام، أو تكلم بصوتك، أو ادخل ابتكار لتصميم من الصفر.",
    bodyEn: "Upload inspiration, speak with voice, or open Innovate to design from scratch.",
    placement: "auto",
    openAi: true,
    caveatAr: "الجولة لا تطلب الميكروفون تلقائيًا — يُطلب فقط عند تفعيل الصوت بنفسك.",
    caveatEn: "This tour never requests the microphone — only when you activate Voice yourself.",
  },
  {
    id: "innovate",
    target: "[data-tour='home-innovate']",
    titleAr: "عندك فكرة في بالك؟",
    titleEn: "Have an idea in mind?",
    bodyAr: "ما لقيت شيء يعجبك؟ ابتكر تصميمك مع الذكاء: فكرة → تعديل → معاينة → إرسال للخياط.",
    bodyEn: "Nothing fits? Create with AI: idea → refine → preview → send to tailor.",
    placement: "auto",
    openAi: true,
    demo: "design-collab",
    caveatAr: "معاينة التصميم ليست منتج سوق، وليست ضمان تصنيع.",
    caveatEn: "Design preview is not a marketplace product and not a manufacturing guarantee.",
  },
  {
    id: "design",
    titleAr: "من الفكرة إلى التنفيذ",
    titleEn: "From idea to make",
    bodyAr: "احفظ مقاساتك، شاهد نظرة افتراضية إن توفّرت، ثم أرسل المواصفات للخياط ليقرر إمكانية التنفيذ.",
    bodyEn: "Save measurements, use Virtual Look when available, then send specs — the tailor decides feasibility.",
    placement: "center",
    demo: "order-flow",
    caveatAr: "النظرة الافتراضية و3D يظهران فقط عند تفعيل المزود / توفر النموذج — لا ندّعي ما هو غير متاح.",
    caveatEn: "Virtual Look and 3D appear only when configured/available — we never pretend otherwise.",
  },
  {
    id: "orders",
    titleAr: "تابع طلبك",
    titleEn: "Track your order",
    bodyAr: "من إرسال الطلب إلى التسليم — تتبّع الحالة في طلباتي. يمكن إعادة الطلب بنفس الذوق لاحقًا.",
    bodyEn: "From send to delivery — track status in My Orders. Reorder the same look later.",
    placement: "center",
    demo: "order-flow",
    caveatAr: "الجولة لا تنشئ طلبًا وهميًا في حسابك.",
    caveatEn: "This tour never creates a fake order in your account.",
  },
  {
    id: "finish",
    titleAr: "جاهز تبدأ؟",
    titleEn: "Ready to begin?",
    bodyAr: "فكرتك تبدأ منك. اكتشف المتاجر، وافتح مستشارك الذكي متى احتجت.",
    bodyEn: "Your idea starts with you. Explore stores, and open AI whenever you need it.",
    placement: "center",
    demo: "summary",
  },
];

/** Customer dashboard tour — /customer */
export const CUSTOMER_TOUR_STEPS: TourStep[] = [
  {
    id: "customer-welcome",
    target: "[data-tour='customer-hero']",
    titleAr: "لوحة العميل",
    titleEn: "Your customer hub",
    bodyAr: "هذه مساحتك الشخصية في خياطك: صِف ما تريد، استكشف الخياطين، وتابع تصميمك وطلباتك من مكان واحد.",
    bodyEn: "This is your personal space on Khayyatak: describe what you want, explore tailors, and follow design and orders in one place.",
    placement: "auto",
  },
  {
    id: "customer-nav",
    target: "[data-tour='customer-nav']",
    titleAr: "تنقّل سريع",
    titleEn: "Quick navigation",
    bodyAr: "من هنا تصل إلى ابتكار، الذكاء، الاستوديو، الطلبات، وحسابك — كل أدوات العميل في شريط واحد.",
    bodyEn: "From here reach Innovate, AI, the studio, orders, and your account — all customer tools in one bar.",
    placement: "auto",
  },
  {
    id: "customer-concierge",
    target: "[data-tour='customer-concierge']",
    titleAr: "قل ماذا تريد",
    titleEn: "Tell us what you want",
    bodyAr: "اكتب فكرتك — مثل «دشداشة بيضاء رسمية» أو «عباية سوداء مفتوحة» — لنقترح التصميم والخياطين المناسبين.",
    bodyEn: "Write your idea — e.g. a formal white dishdasha — and we’ll suggest design and matching tailors.",
    placement: "auto",
  },
  {
    id: "customer-tailors",
    target: "[data-tour='customer-tailors']",
    titleAr: "خياطون حقيقيون",
    titleEn: "Real tailors",
    bodyAr: "قائمة الخياطين هنا من المتاجر المسجّلة فعليًا. اختر من يناسب ذوقك ومدينتك.",
    bodyEn: "This tailor list comes from real registered stores. Pick who fits your style and city.",
    placement: "auto",
    caveatAr: "إن كانت القائمة فارغة، تظهر متاجر تجريبية للمظهر فقط.",
    caveatEn: "If the live list is empty, labeled demo stores appear for appearance.",
  },
  {
    id: "customer-innovate",
    target: "[data-tour='customer-nav-innovate']",
    titleAr: "ابتكار تصميمك",
    titleEn: "Innovate your design",
    bodyAr: "اختر عباية أو دشداشة، صف فكرتك، عدّل الأجزاء، ثم أرسل المشروع للخياط لمراجعة التنفيذ.",
    bodyEn: "Choose abaya or dishdasha, describe your idea, edit parts, then send the project to a tailor for feasibility.",
    placement: "auto",
  },
  {
    id: "customer-design",
    target: "[data-tour='customer-design']",
    titleAr: "تصميمك الحالي",
    titleEn: "Your current design",
    bodyAr: "هنا ترى ملخص التصميم التوضيحي. افتح الاستوديو لتعديله قبل إرساله.",
    bodyEn: "Here you see a concept summary of your design. Open the studio to refine it before sending.",
    placement: "auto",
    caveatAr: "المعاينة تصميم توضيحي — ليست منتج سوق.",
    caveatEn: "This preview is a design concept — not a marketplace product.",
  },
  {
    id: "customer-orders",
    target: "[data-tour='customer-nav-orders']",
    titleAr: "تابع طلباتك",
    titleEn: "Track your orders",
    bodyAr: "بعد الإرسال للخياط، تابع حالة الطلب من «الطلبات» حتى التسليم.",
    bodyEn: "After you send to a tailor, track status under Orders until delivery.",
    placement: "auto",
  },
  {
    id: "customer-finish",
    titleAr: "جاهز تستكشف؟",
    titleEn: "Ready to explore?",
    bodyAr: "ابدأ من المساعد أعلاه، أو ادخل ابتكار لتصميم من الصفر. يمكنك إعادة هذه الجولة من حسابي في أي وقت.",
    bodyEn: "Start from the concierge above, or open Innovate to design from scratch. You can replay this tour anytime from your profile.",
    placement: "center",
    demo: "summary",
  },
];
